//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.HttpsServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDTO", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceTier")]
    [System.SerializableAttribute()]
    public partial class UserDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BoostsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateRegisteredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReservationsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Boosts {
            get {
                return this.BoostsField;
            }
            set {
                if ((this.BoostsField.Equals(value) != true)) {
                    this.BoostsField = value;
                    this.RaisePropertyChanged("Boosts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateRegistered {
            get {
                return this.DateRegisteredField;
            }
            set {
                if ((this.DateRegisteredField.Equals(value) != true)) {
                    this.DateRegisteredField = value;
                    this.RaisePropertyChanged("DateRegistered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PictureURL {
            get {
                return this.PictureURLField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureURLField, value) != true)) {
                    this.PictureURLField = value;
                    this.RaisePropertyChanged("PictureURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Reservations {
            get {
                return this.ReservationsField;
            }
            set {
                if ((this.ReservationsField.Equals(value) != true)) {
                    this.ReservationsField = value;
                    this.RaisePropertyChanged("Reservations");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Post", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Post : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatePostedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastEditedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatePosted {
            get {
                return this.DatePostedField;
            }
            set {
                if ((this.DatePostedField.Equals(value) != true)) {
                    this.DatePostedField = value;
                    this.RaisePropertyChanged("DatePosted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageSource {
            get {
                return this.ImageSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageSourceField, value) != true)) {
                    this.ImageSourceField = value;
                    this.RaisePropertyChanged("ImageSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastEdited {
            get {
                return this.LastEditedField;
            }
            set {
                if ((this.LastEditedField.Equals(value) != true)) {
                    this.LastEditedField = value;
                    this.RaisePropertyChanged("LastEdited");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HttpsServiceReference.ISocialAdService")]
    public interface ISocialAdService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/Register", ReplyAction="http://tempuri.org/ISocialAdService/RegisterResponse")]
        void Register(string email, string password, string name, string pictureURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/Register", ReplyAction="http://tempuri.org/ISocialAdService/RegisterResponse")]
        System.Threading.Tasks.Task RegisterAsync(string email, string password, string name, string pictureURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/Authenticate", ReplyAction="http://tempuri.org/ISocialAdService/AuthenticateResponse")]
        void Authenticate(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/Authenticate", ReplyAction="http://tempuri.org/ISocialAdService/AuthenticateResponse")]
        System.Threading.Tasks.Task AuthenticateAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/GetAuthenticatedUser", ReplyAction="http://tempuri.org/ISocialAdService/GetAuthenticatedUserResponse")]
        ConsoleClient.HttpsServiceReference.UserDTO GetAuthenticatedUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/GetAuthenticatedUser", ReplyAction="http://tempuri.org/ISocialAdService/GetAuthenticatedUserResponse")]
        System.Threading.Tasks.Task<ConsoleClient.HttpsServiceReference.UserDTO> GetAuthenticatedUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/LogOut", ReplyAction="http://tempuri.org/ISocialAdService/LogOutResponse")]
        void LogOut();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/LogOut", ReplyAction="http://tempuri.org/ISocialAdService/LogOutResponse")]
        System.Threading.Tasks.Task LogOutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/GetUser", ReplyAction="http://tempuri.org/ISocialAdService/GetUserResponse")]
        ConsoleClient.HttpsServiceReference.UserDTO GetUser(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/GetUser", ReplyAction="http://tempuri.org/ISocialAdService/GetUserResponse")]
        System.Threading.Tasks.Task<ConsoleClient.HttpsServiceReference.UserDTO> GetUserAsync(string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/CountUsers", ReplyAction="http://tempuri.org/ISocialAdService/CountUsersResponse")]
        int CountUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/CountUsers", ReplyAction="http://tempuri.org/ISocialAdService/CountUsersResponse")]
        System.Threading.Tasks.Task<int> CountUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/GetUsers", ReplyAction="http://tempuri.org/ISocialAdService/GetUsersResponse")]
        ConsoleClient.HttpsServiceReference.UserDTO[] GetUsers(int skip, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/GetUsers", ReplyAction="http://tempuri.org/ISocialAdService/GetUsersResponse")]
        System.Threading.Tasks.Task<ConsoleClient.HttpsServiceReference.UserDTO[]> GetUsersAsync(int skip, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/getData", ReplyAction="http://tempuri.org/ISocialAdService/getDataResponse")]
        int getData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/getData", ReplyAction="http://tempuri.org/ISocialAdService/getDataResponse")]
        System.Threading.Tasks.Task<int> getDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/GenerateTestPost", ReplyAction="http://tempuri.org/ISocialAdService/GenerateTestPostResponse")]
        ConsoleClient.HttpsServiceReference.Post GenerateTestPost(string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialAdService/GenerateTestPost", ReplyAction="http://tempuri.org/ISocialAdService/GenerateTestPostResponse")]
        System.Threading.Tasks.Task<ConsoleClient.HttpsServiceReference.Post> GenerateTestPostAsync(string content);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocialAdServiceChannel : ConsoleClient.HttpsServiceReference.ISocialAdService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocialAdServiceClient : System.ServiceModel.ClientBase<ConsoleClient.HttpsServiceReference.ISocialAdService>, ConsoleClient.HttpsServiceReference.ISocialAdService {
        
        public SocialAdServiceClient() {
        }
        
        public SocialAdServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SocialAdServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialAdServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialAdServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Register(string email, string password, string name, string pictureURL) {
            base.Channel.Register(email, password, name, pictureURL);
        }
        
        public System.Threading.Tasks.Task RegisterAsync(string email, string password, string name, string pictureURL) {
            return base.Channel.RegisterAsync(email, password, name, pictureURL);
        }
        
        public void Authenticate(string email, string password) {
            base.Channel.Authenticate(email, password);
        }
        
        public System.Threading.Tasks.Task AuthenticateAsync(string email, string password) {
            return base.Channel.AuthenticateAsync(email, password);
        }
        
        public ConsoleClient.HttpsServiceReference.UserDTO GetAuthenticatedUser() {
            return base.Channel.GetAuthenticatedUser();
        }
        
        public System.Threading.Tasks.Task<ConsoleClient.HttpsServiceReference.UserDTO> GetAuthenticatedUserAsync() {
            return base.Channel.GetAuthenticatedUserAsync();
        }
        
        public void LogOut() {
            base.Channel.LogOut();
        }
        
        public System.Threading.Tasks.Task LogOutAsync() {
            return base.Channel.LogOutAsync();
        }
        
        public ConsoleClient.HttpsServiceReference.UserDTO GetUser(string userId) {
            return base.Channel.GetUser(userId);
        }
        
        public System.Threading.Tasks.Task<ConsoleClient.HttpsServiceReference.UserDTO> GetUserAsync(string userId) {
            return base.Channel.GetUserAsync(userId);
        }
        
        public int CountUsers() {
            return base.Channel.CountUsers();
        }
        
        public System.Threading.Tasks.Task<int> CountUsersAsync() {
            return base.Channel.CountUsersAsync();
        }
        
        public ConsoleClient.HttpsServiceReference.UserDTO[] GetUsers(int skip, int amount) {
            return base.Channel.GetUsers(skip, amount);
        }
        
        public System.Threading.Tasks.Task<ConsoleClient.HttpsServiceReference.UserDTO[]> GetUsersAsync(int skip, int amount) {
            return base.Channel.GetUsersAsync(skip, amount);
        }
        
        public int getData() {
            return base.Channel.getData();
        }
        
        public System.Threading.Tasks.Task<int> getDataAsync() {
            return base.Channel.getDataAsync();
        }
        
        public ConsoleClient.HttpsServiceReference.Post GenerateTestPost(string content) {
            return base.Channel.GenerateTestPost(content);
        }
        
        public System.Threading.Tasks.Task<ConsoleClient.HttpsServiceReference.Post> GenerateTestPostAsync(string content) {
            return base.Channel.GenerateTestPostAsync(content);
        }
    }
}
